
# Stage 1: Compile and Build angular codebase

# Use official node alpine image as the base image
FROM node:alpine as build

# Set the working directory
WORKDIR /app

# Add source code to working directory
COPY . .

# Build the angular app in production mode and store the artifacts in dist folder
RUN npm run build-admin
# Stage 2: Serve app with nginx server
FROM nginx:alpine as production

#copy /dist/apps/admin from build stage to /usr/share/nginx/html of production stage
COPY --from=build /app/dist/apps/admin /usr/share/nginx/html

#expose port 80
EXPOSE 80

LABEL org.opencontainers.image.source https://github.com/PlaySystems-Integrator/Play.App
