import { MbamOneViewGetAllDetectionsResponseModelRemoteIntrusionDetectionAndPrevention } from '@play.app/types/Mbam/MbamOneViewGetAllDetectionsResponseModelRemoteIntrusionDetectionAndPrevention';

export interface MbamOneViewGetAllDetectionsResponseModelPlugins {
  RemoteIntrusionDetectionAndPrevention: MbamOneViewGetAllDetectionsResponseModelRemoteIntrusionDetectionAndPrevention;
  EndpointProtection: MbamOneViewGetAllDetectionsResponseModelRemoteIntrusionDetectionAndPrevention;
  AssetManager: MbamOneViewGetAllDetectionsResponseModelRemoteIntrusionDetectionAndPrevention;
  WindowsRemoteIntrusionDetectionAndPrevention: MbamOneViewGetAllDetectionsResponseModelRemoteIntrusionDetectionAndPrevention;
  EndpointDetectionAndResponse: MbamOneViewGetAllDetectionsResponseModelRemoteIntrusionDetectionAndPrevention;
}
